#! /bin/bash
mkdir -p DATA
curl 'https://servicios3.abc.gob.ar/valoracion.docente/api/apd.oferta.encabezado/select?q=*%3A*&rows=1000&facet=true&facet.field=descdistrito&facet.field=descnivelmodalidad&facet.field=cargo&facet.field=estado&facet.limit=200&facet.mincount=1&json.nl=map&fq=descdistrito%3Aberazategui%20quilmes%20avellaneda&fq=cargo%3A*construccion*de*ciudadania*%20*COMUNICACI*%20*taller*lenguajes*%20*observatorio*medios*%20*OCL*%20*precep*&fq=estado:Publicada&wt=csv' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: es-AR,es;q=0.8,en-US;q=0.5,en;q=0.3' --compressed -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' > test1.csv;
sleep 10;
iconv -f iso-8859-1 -t UTF-8//TRANSLIT test1.csv -o "./DATA/datos_crudos-$(date +"%d-%m-%Y").csv";
rm test1.csv;



