name: Ejecutar ScriptBusqueda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar csvkit
        run: sudo apt-get update && sudo apt-get install -y csvkit

      - name: Dar permisos de ejecución al script
        run: chmod +x ScriptBusqueda

      - name: Ejecutar el script
        run: ./ScriptBusqueda
