name: Ejecutar ScriptBusqueda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Actualizar
        run: sudo apt-get update 

      - name: Dar permisos de ejecución al script
        run: chmod +x ScriptBusqueda

      - name: Ejecutar el script
        run: ./ScriptBusqueda

      - name: Agregar el archivo CSV generado
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add test1_utf8.csv
          git commit -m "Agregar archivo CSV generado por ScriptBusqueda"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/atm44/ABC_reporte.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
