name: Ejecutar ScriptBusqueda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Actualizar
        run: sudo apt-get update 

      - name: Dar permisos de ejecución al script
        run: chmod +x ScriptBusqueda

      - name: Ejecutar el script
        run: ./ScriptBusqueda

      - name: Agregar el archivo CSV generado
        run: |
          echo ${{ secrets.PAT_TOKEN }}
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull
          echo "pull ok"
          git add test1_utf8.csv
          git commit -m "Agregar archivo CSV generado por ScriptBusqueda"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/atm44/ABC_reporte.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the version of Python to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
      - name: Send CSV via email
        run: |
          python send_email.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
