name: Ejecutar ScriptBusqueda

on:
  schedule:
    - cron: "30 21 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Actualizar
        run: sudo apt-get update 


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the version of Python to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install tabulate
      - name: Send CSV via email
        run: |
          python send_email.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SEND: ${{ vars.EMAIL_SEND }}
          SMTP_SERVER: ${{ vars.SMTP_SERVER }}
          SMTP_PORT: ${{ vars.SMTP_PORT }}
